# Generated by Django 5.1.1 on 2024-10-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_patientmetadata_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmetadata',
            name='medicine',
        ),
        migrations.AddField(
            model_name='patientmetadata',
            name='medicine',
            field=models.TextField(default='[]'),
        ),
    ]
